Custom dockerfile, docker-compose for image prod build. Update GHA pages-gh.yaml to build image

diff --git a/.github/workflows/pages-gh.yml b/.github/workflows/pages-gh.yml
--- a/.github/workflows/pages-gh.yml
+++ b/.github/workflows/pages-gh.yml
@@ -64,7 +64,6 @@ jobs:
       contents: read
     
     steps:
-    # GH Actions
       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
         with:
@@ -91,8 +90,8 @@ jobs:
       - name: Build with Hugo
         env:
           # For maximum backward compatibility with Hugo modules
-          HUGO_ENVIRONMENT: production
-          HUGO_ENV: production
+          HUGO_ENVIRONMENT: staging
+          HUGO_ENV: staging
         run: |
           hugo \
             --gc \
@@ -124,6 +123,176 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
+
+  # Create and publish a prod docker image          
+  build_and_push_prod_image:
+    environment: docker-image
+
+    if: github.ref == 'refs/heads/main'
+    needs:
+      - generate-timestamp
+      - build-website
+    env:
+      HUGO_VERSION: 0.139.4 # latest  #  0.126.1 
+      HUGO_FORMS: ${{ vars.HUGO_FORMS }}
+      HUGO_GOOGLEANALYTICS: ${{ vars.HUGO_GOOGLEANALYTICS }}
+      
+      REGISTRY: ghcr.io # docker.github.sfu.ca 
+      IMAGE_NAME: ${{ github.repository }}
+
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+      # This is used to complete the identity challenge
+      # with sigstore/fulcio when running outside of PRs.
+      id-token: write
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: true  # Fetch Hugo themes (true OR recursive) # failing on ubuntu container
+          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
+          # set-safe-directory: '/__w/coastal-science.github.io/coastal-science.github.io'
+          
+      - name: Set safe directory workaround
+        run: |
+          git config --global --add safe.directory /__w/coastal-science.github.io/coastal-science.github.io
+      
+      - name: Generate tags
+        id: tags
+        run: |
+            # Get the current branch name
+            branch_name=$(git rev-parse --abbrev-ref HEAD)
+            # docker tag limit is 128 characters
+            # The timestamp (YYYY_MM_DD_HH_MM_SS), commit id (7), 
+            # and punctuation (additional _) take up 29 characters.
+            # For 3 catalogs the branch names is can occupy the 
+            # remaining characters = floor((128-29*3)/3) = 13
+            branch_name=${branch_name:0:13} 
+
+            # Get the abbreviated commit hash
+            commit_hash=$(git rev-parse --short HEAD)
+            
+            # Get the current commit datetime (without timezone)
+            commit_date=$(git show -s --format=%ci HEAD)
+            
+            # remove last five characters (timezone information)
+            commit_date=${commit_date:0:${#commit_date}-5} #-5 digits causes 'expression < 0' error. Instead dynamically get the string length.
+            
+            
+            # Combine the parts into the desired format
+            result="${branch_name}_${commit_hash}_${commit_date}"
+            
+            # remove leading/trailing spaces
+            # formatted_result=$(awk '{$1=$1;print}')
+            formatted_result=$(echo $result | xargs)
+            # Replace spaces, colons, and dashes with underscores
+            formatted_result=$(echo "$formatted_result" | sed 's/[ :\-]/_/g')
+            
+            branch_name=$(echo $branch_name | xargs)
+            branch_name=$(echo "$branch_name" | sed 's/[ :\-]/_/g')
+            
+            commit_hash=$(echo $commit_hash | xargs)
+            commit_hash=$(echo "$commit_hash" | sed 's/[ :\-]/_/g')
+            
+            commit_date=$(echo $commit_date | xargs)
+            commit_date=$(echo "$commit_date" | sed 's/[ :\-]/_/g')
+            
+            # Print the final result and return it
+            echo "$formatted_result"
+            
+            echo "TAG=${TAG-random}" >> "$GITHUB_OUTPUT"
+            echo "EXTRA_TAG=${EXTRA_TAG}" >> "$GITHUB_OUTPUT"
+            echo "branch_name=${branch_name}" >> "$GITHUB_OUTPUT"
+            echo "commit_hash=${commit_hash}" >> "$GITHUB_OUTPUT"
+            echo "commit_date=${commit_date}" >> "$GITHUB_OUTPUT"
+
+      # GH Actions
+      - name: Setup Hugo
+        uses: peaceiris/actions-hugo@v2
+        with:
+          hugo-version: ${{ env.HUGO_VERSION }}
+          extended: true
+
+      - name: Build and Minify with Hugo
+        env:
+          # For maximum backward compatibility with Hugo modules
+          HUGO_ENVIRONMENT: production
+          HUGO_ENV: production
+        run: |
+          hugo \
+            --gc \
+            --minify \
+            --baseURL "${{ env.HUGO_BASEURL }}/"
+      
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+     
+      # Login against a Docker registry except on PR
+      # https://github.com/docker/login-action
+      - name: Log into registry ${{ env.REGISTRY }}
+        if: github.event_name != 'pull_request'
+        uses: docker/login-action@v3 #343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      # Extract metadata (tags, labels) for Docker
+      # https://github.com/docker/metadata-action
+      - name: Extract Docker metadata
+        id: meta
+        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
+        with:
+          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+
+      - name: Build website with Dockerfile.prod
+        run: |
+          docker compose -f docker-compose.yml -f docker-compose.override.yml build website
+          docker tag website ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
+          docker tag website ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.branch_name }}
+          docker tag website ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.commit_hash }}
+          docker tag website ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.commit_date }}
+          
+          docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+  
+  # Create and publish a prod docker image          
+  deploy_prod_image:
+    environment: docker-image
+
+    if: github.ref == 'refs/heads/main'
+    needs:
+      - build_and_push_prod_image
+    env:      
+      REGISTRY: ghcr.io # docker.github.sfu.ca 
+      IMAGE_NAME: ${{ github.repository }}
+
+    runs-on: self-hosted
+    permissions:
+      contents: read
+      packages: read
+      
+    steps:
+      - name: Deploy backend nomad job
+        run: |
+          echo "Attempting backend deployment: population=${{ env.IMAGE_NAME }}"
+          
+          # cd call-library/nomad/
+
+          # export POPULATION=${{ vars.POPULATION }}; 
+          # export TYPE=${{ steps.type-of-build.outputs.TYPE_OF_BUILD }}; 
+          # envsubst < call-catalogue-single.nomad.template > $POPULATION-call-catalogue-$TYPE.nomad
+
+          # nomad job stop -address="http://192.168.245.224:4646" -token=${{ secrets.NOMAD_TOKEN }} \
+          #     $POPULATION-call-catalogue-$TYPE || true
+          # nomad run -verbose -address="http://192.168.245.224:4646" -token=${{ secrets.NOMAD_TOKEN }} \
+          #     -var "type=${{ steps.type-of-build.outputs.TYPE_OF_BUILD }}" \
+          #     -var "population=${{ vars.POPULATION }}" \
+          #     $POPULATION-call-catalogue-$TYPE.nomad
+
+          # echo deployed to https://${{ vars.POPULATION }}-${{ steps.type-of-build.outputs.TYPE_OF_BUILD }}.***.***.ca
+          # cd -
 
   # Create and publish a docker image          
   build_and_push_image:
